### ISSUE TITLE
UDP server.stop() throws socket.destroy not a function second time it is called

### ISSUE THREAD

**Issue by RIAEvangelist** [RIAEvangelist/node-ipc#62]
```sh

    /home/bmiller/git/node-ipc/lib/socketServer.js:9
    __cov_lfQLJ50Tpas4nzNlJdRiUw.s['1']++;var net=require('net'),tls=require('tls'),fs=require('fs'),dgram=require('dgram'),eventParser=require('../lib/eventParser.js'),pubsub=require('event-pubsub'),Message=require('js-message');function emit(socket,type,data){__cov_lfQLJ50Tpas4nzNlJdRiUw.f['1']++;__cov_lfQLJ50Tpas4nzNlJdRiUw.s['3']++;this.log('dispatching event to socket'.debug,' : ',type.data,data);__cov_lfQLJ50Tpas4nzNlJdRiUw.s['4']++;var message=new Message();__cov_lfQLJ50Tpas4nzNlJdRiUw.s['5']++;message.type=type;__cov_lfQLJ50Tpas4nzNlJdRiUw.s['6']++;message.data=data;__cov_lfQLJ50Tpas4nzNlJdRiUw.s['7']++;if(this.config.rawBuffer){__cov_lfQLJ50Tpas4nzNlJdRiUw.b['1'][0]++;__cov_lfQLJ50Tpas4nzNlJdRiUw.s['8']++;message=new Buffer(type,this.encoding);}else{__cov_lfQLJ50Tpas4nzNlJdRiUw.b['1'][1]++;__cov_lfQLJ50Tpas4nzNlJdRiUw.s['9']++;message=eventParser.format(message);}__cov_lfQLJ50Tpas4nzNlJdRiUw.s['10']++;if((__cov_lfQLJ50Tpas4nzNlJdRiUw.b['3'][0]++,this.udp

    TypeError: socket.destroy is not a function
        at Object.<anonymous> (/home/bmiller/git/node-ipc/lib/socketServer.js:9:15989)
        at Object.pub (/home/bmiller/git/node-ipc/node_modules/event-pubsub/event-pubsub.js:69:19)
        at Object.trigger (/home/bmiller/git/node-ipc/node_modules/event-pubsub/event-pubsub.js:111:21)
        at Socket.<anonymous> (/home/bmiller/git/node-ipc/lib/socketServer.js:9:9217)
        at emitNone (events.js:67:13)
        at Socket.emit (events.js:166:7)
        at socketCloseNT (dgram.js:366:8)
        at doNTCallback1 (node.js:430:9)
        at process._tickCallback (node.js:352:17)

```

**Comment by RIAEvangelist** [comment]
invalid issue. problem was with test.

**Comment by RIAEvangelist** [comment]
fixed.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
